### ISSUE TITLE
RP2040 Build fails when compiling serial.c

### ISSUE THREAD

**Issue by howitzer-88** [grblHAL/RP2040#12]
[err.log](https://github.com/grblHAL/core/files/7660283/err.log)
Please see the attached error log. Previous versions compile fine. Seems to be related to the recent changes with the core. Using 'make -k' everything else builds fine.

**Comment by terjeio** [comment]
Oops, I have missed this one. Until I commit a fix change

https://github.com/grblHAL/RP2040/blob/e1fb16a2930a5215b5b7794f786202e3e37d2f4c/serial.c#L466
to
` .state.connected = true, `

Sorry for the trouble.

**Comment by howitzer-88** [comment]
Also need to apply that to line 236.

**Comment by terjeio** [comment]
I have now commited a fix. Thanks for reporting.
