### ISSUE TITLE
RP2040 VFD

### ISSUE THREAD

**Issue by BobbyDD** [grblHAL/RP2040#26]
Hi,
i need some help to activate the VFD spindle module for the RP2040.
i copied the spindle folder in the RP2040 folder an add #define VFD_ENABLE 1 in my_machine.h
And now, i get some compiling error.

`[build] /home/trocker/Projekte/RP2040/driver.c: In function 'driver_init':
[build] /home/trocker/Projekte/RP2040/driver.c:1997:5: warning: implicit declaration of function 'modbus_init' [-Wimplicit-function-declaration]
[build]  1997 |     modbus_init(serial2Init(115200));
[build]       |     ^~~~~~~~~~~
[build] In file included from /home/trocker/Projekte/RP2040/driver.c:2004:
[build] /home/trocker/Projekte/RP2040/grbl/plugins_init.h:32:17: warning: conflicting types for 'modbus_init'
[build]    32 |     extern void modbus_init (void);
[build]       |                 ^~~~~~~~~~~
[build] /home/trocker/Projekte/RP2040/driver.c:1997:5: note: previous implicit declaration of 'modbus_init' was here
[build]  1997 |     modbus_init(serial2Init(115200));
[build]       |     ^~~~~~~~~~~
[build] [ 28%] Linking CXX executable grblHAL.elf
[build] /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/grblHAL.dir/driver.c.obj: in function `driver_init':
[build] /home/trocker/Projekte/RP2040/driver.c:1997: undefined reference to `modbus_init'
[build] /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: CMakeFiles/grblHAL.dir/driver.c.obj: in function `driver_init':
[build] /home/trocker/Projekte/RP2040/grbl/plugins_init.h:33: undefined reference to `modbus_init'
[build] /usr/lib/gcc/arm-none-eabi/9.2.1/../../../arm-none-eabi/bin/ld: /home/trocker/Projekte/RP2040/grbl/plugins_init.h:39: undefined reference to `vfd_huanyang_init'
[build] collect2: error: ld returned 1 exit status
[build] make[3]: *** [CMakeFiles/grblHAL.dir/build.make:1872: grblHAL.elf] Fehler 1
[build] make[2]: *** [CMakeFiles/Makefile2:1590: CMakeFiles/grblHAL.dir/all] Fehler 2
[build] make[1]: *** [CMakeFiles/Makefile2:1597: CMakeFiles/grblHAL.dir/rule] Fehler 2
[build] make: *** [Makefile:144: grblHAL] Fehler 2
[build] Build finished with exit code 2`

I hope you can help me.
Thx

**Comment by terjeio** [comment]
There are several code small changes and also additions to CMakeLists.txt that has to be made to make this possible.

> I hope you can help me.

Give me a bit of time, I have been very busy recently so have a bit of a backlog to clear.
