### ISSUE TITLE
HAS_IOPORTS should be on every map?

### ISSUE THREAD

**Issue by aselle** [grblHAL/RP2040#59]
I am using something similar to the PI Pico Bob. I was trying to add the VFD spindle, but to make it work with my hardware (where I have a direction pin that is an auxiliary pin), I needed to #define HAS_IOPORTS in my map file or mymachine.h. Otherwise, I was getting a hang (probably a fatal alert) whenever the spindle plugin tried to claim the ioport.

It seems like there is not much harm in #defining this by default in generic_map.h and all other maps? Happy to contribute patch if that is the "right thing" to do? 

@andrewmarles,  you have any opinion?

**Comment by terjeio** [comment]
The HAS_IOPORTS define has now been replaced with other guarding defines where needed.

**Comment by aselle** [comment]
Thank you!
