### ISSUE TITLE
RP2040 Zero

### ISSUE THREAD

**Issue by Juank23** [grblHAL/RP2040#62]
Good morning, my friend I acquired a pico zero a few days ago and I generated the binary through the Web Builder page, and it works but the pins are different to the ones that my board has, I downloaded the code for vscode but I have not been able to compile it, thanks for your help.
![RP2040-Zero](https://github.com/grblHAL/RP2040/assets/32020092/c37a829e-7b09-4026-adab-741927f1e65e)

**Comment by Juank23** [comment]
thanks for your ptonta respusta, it is necessary to install something to the vscode so that it can compile the firmware for the pico zero....
![vscode](https://github.com/grblHAL/RP2040/assets/32020092/098c37b3-ef3e-409c-8e9a-2869584c8909)

**Comment by terjeio** [comment]
> it is necessary to install something to the vscode so that it can compile the firmware for the pico zero....

Yes, a toolchain and the SDK has to be installed, follow the link in the [readme](https://github.com/grblHAL/RP2040/blob/master/README.md). And there are relevant links in the search I provided above.

**Comment by andrewmarles** [comment]
Under windows I have found this script to work well:

https://github.com/raspberrypi/pico-setup-windows

**Comment by Juank23** [comment]
good day, I tried all the steps but it still doesn't work, is there any way to change the pinout for my pico Zero I remain attentive thank you.....

**Comment by terjeio** [comment]
Create a file name _my_machine_map.h_ with the pin map in the same directory as the other maps (I would start with a copy of [generic_map.h](https://github.com/grblHAL/RP2040/blob/master/generic_map.h)) and edit it to suit your requirements, then enable it by [uncommenting this line](https://github.com/grblHAL/RP2040/blob/078836e5ff6c2366b095f2602e07ca16b6d09d82/my_machine.h#L31) before compiling.

**Comment by Juank23** [comment]
after a few days I managed to compile the code, thank you very much for your excellent work.

**Comment by terjeio** [comment]
Good to hear that, have fun with your machine!
