### ISSUE TITLE
SKR Pico 2nd uart for vfd control

### ISSUE THREAD

**Issue by crackinx** [grblHAL/RP2040#68]
the BTT SKR Pico has two UARTs, one is for the tmc2209 drivers and the other is meant for direct pi communication. I would like to use the 2nd Uart for vfd control through modbus, but the web builder does not allow me to use the 2nd serial port and gives me an error that only one serial port option can be selected. I wouldn't even know how to implement that into source if I could even get it to compile (lord knows I've tried). Any nudges in the right direction would be greatly appreciated!

**Comment by terjeio** [comment]
Fix commited, I leave it to you to test/verify as I do not have acces to aBTT SKR Pico board.
