### ISSUE TITLE
Enable Macros cause crash

### ISSUE THREAD

**Issue by fireup924** [grblHAL/RP2040#86]
When I enable SDCard/Macros, ioSender would not run and locks up.

When I connect to a terminal program and send a $I, it will cause the board to lock up.

**Comment by terjeio** [comment]
Does not happen for me so need more details.

**Comment by terjeio** [comment]
Which board?
Is it ethernet enabled - but grblHAL compiled without ethernet support?
Asking since mounting the SD card fails for me when there is an ethernet chip on the SPI bus.

> Do I have to format the card a certain way? or use a certain card?

Fat32 formatted, size <= 32GB. Some makes/models of SD cards may fail to mount.

**Comment by fireup924** [comment]
The board does not have pull-up resistors but I'm using it with this SD Card module that has pull-up resistors:

![SDCardModule_](https://github.com/grblHAL/RP2040/assets/56750818/d7d59636-dd47-4e3b-98aa-690b73bf34ca)

**Comment by fireup924** [comment]
I will try a Web Build with just a bare Pi Pico module and this SD Module and see if it works on that...

**Comment by fireup924** [comment]
Turn out my SD Card was not formatted correctly.
